apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-k8s
spec:
  selector:
    matchLabels:
      app: mysql-k8s
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-k8s
    spec:
      containers:
      - image: mysql:5.6
        name: mysql-k8s
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-k8s
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-k8s
